#!/bin/bash

for f in /usr/share/fonts/*
do
    echo "adding fontdir '$f'"
    xset +fp "$f"
done
xset fp rehash

PROFILE="${WM:-xmonad}"

/usr/bin/start-pulseaudio-x11

gpg-agent --daemon --enable-ssh-support \
    --write-env-file "${HOME}/.gpg-agent-info"

. "${HOME}/.gpg-agent-info"
export GPG_AGENT_INFO
export SSH_AUTH_SOCK

CURR_DIR="$RC_DIR"
RC_DIR="$RC_DIR/$PROFILE" \
\
   exec \
   \
   ck-launch-session \
   dbus-launch \
\
"$CURR_DIR"/"$PROFILE"/rc
