#!/bin/bash

for f in /usr/share/fonts/*
do
    echo "adding fontdir '$f'"
    xset +fp "$f"
done
xset fp rehash

PROFILE="${WM:-xmonad}"

/usr/bin/start-pulseaudio-x11

CURR_DIR="$RC_DIR"
RC_DIR="$RC_DIR/$PROFILE" \
\
   exec \
   \
   dbus-launch \
   ssh-agent \
\
"$CURR_DIR"/"$PROFILE"/rc
