#!/usr/bin/env bash

if [[ -f "$HOME/.bashrc" ]] ; then
    source "$HOME/.bashrc"
fi

if [[ -d "$HOME/bin" ]] ; then
    path_prepend "$HOME/bin"
fi

for cfg in vars rc
do
    [[ -f $HOME/.bash/${cfg} ]] && source "$HOME/.bash/${cfg}"
    [[ -f $HOME/.bash/${cfg}.local ]] && source "$HOME/.bash/${cfg}.local"
done

# End ~/.bash/profile
