#!/usr/bin/env bash

# Begin ~/.bash/vars
# Personal aliases and functions.

case "$TERM" in
    screen)
        TERM=screen-256color
        export TERM
        ;;
    xterm)
        TERM=xterm-256color
        export TERM
        ;;
esac

export LANG=ru_RU.UTF-8
export LANGUAGE=ru_BY:ru_RU:ru:en_GB:en
export LC_ALL=""

export G_FILENAME_ENCODING="@locale"
export G_BROKEN_FILENAMES=1
export G_FILENAME_ENCODING G_BROKEN_FILENAMES

export PERLDOC_PAGER="less -isR"

export PAGER="most"
#export PAGER="less"
#export LESS="-isR"

export MAILDIR=$HOME/.maildir

export GROFF_NO_SGR=1
export TSOCKS_CONFFILE=$HOME/.tscoks/conf
export SDL_AUDIODRIVER=pulse
export ECHANGELOG_USER="Sergei Trofimovich <slyfox@gentoo.org>"

#https://bugs.gentoo.org/show_bug.cgi?id=517342
export PROMPT_COMMAND=

#End ~/.bash/vars
