#!/usr/bin/env bash

# Begin ~/.bash/vars
# Personal aliases and functions.

if [ "$TERM" = "rxvt-unicode" ] ; then
        export TERM=rxvt
fi

if [ "$TERM" = "xterm" ] ; then
        export TERM=xterm-color
        export COLORTERM=xterm
fi

if [ "$TERM" = "xterm-color" ] ; then
        export COLORTERM=xterm
fi

export LANG=ru_RU.UTF-8
export LANGUAGE=ru_BY:ru_RU:ru:en_GB:en
export LC_ALL=""

export G_FILENAME_ENCODING="@locale"
export G_BROKEN_FILENAMES=1
export G_FILENAME_ENCODING G_BROKEN_FILENAMES

export PERLDOC_PAGER="less -isR"

export PAGER="most"
#export PAGER="less"
#export LESS="-isR"

export MAILDIR=$HOME/.maildir

export GROFF_NO_SGR=1
export TSOCKS_CONFFILE=$HOME/.tscoks/conf
export SDL_AUDIODRIVER=pulse
export ECHANGELOG_USER="Sergei Trofimovich <slyfox@gentoo.org>"

#https://bugs.gentoo.org/show_bug.cgi?id=517342
export PROMPT_COMMAND=

if [[ -f ${HOME}/.gpg-agent-info ]]; then
   . "${HOME}/.gpg-agent-info"
   export GPG_AGENT_INFO
   export SSH_AUTH_SOCK
fi

#End ~/.bash/vars
