#!/bin/sh

xset m 1 1
#xset m 4
xset r rate 200 40

# left and down arrows
xset r 113 r 116

xsetroot -cursor_name left_ptr

setxkbmap -model pc105 -layout us,ru -option grp:caps_toggle

xmodmap ~/.Xmodmap
