[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x000060"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[env]
TERM = "xterm-256color"

[font]
normal.family = "Source Code Pro"
size = 13.0
# space around glyph
offset = { x = -2, y = -4 }
# glyph offset within the cell
glyph_offset = { x = -1, y = -2 }

[keyboard]
bindings = [
  # mimic xterm / xterm-256color
  { key = "Insert",   mods = "Shift",     action = "Paste" },
  { key = "Up",       mods = "Control",   chars = "\u001B[1;5A" },
  { key = "Down",     mods = "Control",   chars = "\u001B[1;5B" },
  { key = "End",      mods = "Control",   chars = "\u001B[1;5F" },
  { key = "Home",     mods = "Control",   chars = "\u001B[1;5H" },
]

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
