[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.whitespace.characters]
tab = ">"
tabpad = "-"

[keys.insert]
C-c = "normal_mode"

[keys.normal]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"
