# spell checker
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
auto-format = false

[language-server.rust-analyzer.config]
check.command = "clippy"
